/**
 * This file is autogenerated by ETH Mobile.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from '../src/utils/eth-mobile/contract';

const deployedContracts = {
  31337: {
    YourContract: {
      address: '0x700b6a60ce7eaaea56f065753d8dcb9653dbad35',
      abi: [
        {
          type: 'constructor',
          inputs: [
            {
              name: '_owner',
              type: 'address',
              internalType: 'address'
            }
          ],
          stateMutability: 'nonpayable'
        },
        {
          type: 'function',
          name: 'owner',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'address',
              internalType: 'address'
            }
          ],
          stateMutability: 'view'
        }
      ],
      inheritedFunctions: {},
      deploymentFile: 'run-1763759612863.json',
      deploymentScript: 'Deploy.s.sol'
    }
  }
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
